'use client'
import { useState, useEffect } from 'react'
import { X, ChevronRight, ChevronLeft } from 'lucide-react'

interface TourStep {
  title: string
  description: string
  emoji: string
}

const STUDENT_TOUR_STEPS: TourStep[] = [
  { title: 'Welcome to ZimLearn! 🎓', description: 'Your personalised ZIMSEC study platform. Let us show you around in 30 seconds.', emoji: '🎓' },
  { title: 'My Subjects', description: 'See all your enrolled ZIMSEC subjects. Click any subject to access lessons, quizzes, and AI tutoring.', emoji: '📚' },
  { title: 'AI Tutor', description: 'Ask EduZim AI any ZIMSEC question anytime. It knows every subject and teaches exactly how ZIMSEC examiners mark.', emoji: '🤖' },
  { title: 'Study Planner', description: 'Get a personalised revision schedule generated by AI based on your exam date and weak topics.', emoji: '📅' },
  { title: 'Progress Tracker', description: 'See your mastery level for every topic, your quiz scores, and predicted grade for each subject.', emoji: '📈' },
  { title: 'You\'re ready! 🚀', description: 'Start by clicking on a subject below. Good luck with your ZIMSEC studies!', emoji: '🚀' },
]

export function OnboardingTour({ role = 'student' }: { role?: string }) {
  const [visible, setVisible] = useState(false)
  const [step, setStep] = useState(0)
  const storageKey = `tour_done_${role}`

  useEffect(() => {
    const done = localStorage.getItem(storageKey)
    if (!done) {
      const timer = setTimeout(() => setVisible(true), 1500)
      return () => clearTimeout(timer)
    }
  }, [storageKey])

  const dismiss = () => {
    localStorage.setItem(storageKey, '1')
    setVisible(false)
  }

  if (!visible) return null

  const steps = STUDENT_TOUR_STEPS
  const current = steps[step]
  const isLast = step === steps.length - 1

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4 sm:p-0">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={dismiss} />

      {/* Card */}
      <div className="relative bg-white dark:bg-slate-800 rounded-2xl shadow-2xl w-full max-w-sm p-6 animate-fade-in-up">
        <button onClick={dismiss} className="absolute top-4 right-4 p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700 transition">
          <X size={16} className="text-gray-400" />
        </button>

        {/* Step indicator */}
        <div className="flex gap-1.5 mb-5">
          {steps.map((_, i) => (
            <div key={i} className={`h-1.5 rounded-full transition-all duration-300 ${i === step ? 'bg-emerald-500 w-6' : i < step ? 'bg-emerald-300 w-3' : 'bg-gray-200 dark:bg-slate-600 w-3'}`} />
          ))}
        </div>

        <div className="text-4xl mb-3">{current.emoji}</div>
        <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-2">{current.title}</h3>
        <p className="text-sm text-gray-500 dark:text-slate-400 leading-relaxed mb-6">{current.description}</p>

        <div className="flex items-center justify-between">
          <button onClick={dismiss} className="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-slate-300 transition">
            Skip tour
          </button>
          <div className="flex gap-2">
            {step > 0 && (
              <button onClick={() => setStep(s => s - 1)} className="flex items-center gap-1 px-3 py-2 rounded-xl border border-gray-200 dark:border-slate-600 text-sm font-medium text-gray-600 dark:text-slate-300 hover:bg-gray-50 dark:hover:bg-slate-700 transition">
                <ChevronLeft size={14} /> Back
              </button>
            )}
            <button
              onClick={isLast ? dismiss : () => setStep(s => s + 1)}
              className="flex items-center gap-1 px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white text-sm font-semibold transition shadow-sm shadow-emerald-200"
            >
              {isLast ? 'Get started' : 'Next'} {!isLast && <ChevronRight size={14} />}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
