'use client'

import { useState } from 'react'
import {
  Crown, Bot, Sparkles, ArrowRight, Loader2, Download,
  BookOpen, Lock, Share2, CheckCircle, Package,
} from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import Link from 'next/link'

const SUBJECTS_BY_LEVEL: Record<string, string[]> = {
  primary: [
    'Mathematics', 'English Language', 'Science and Technology', 'Social Science',
    'Physical Education & Arts', 'Shona', 'Ndebele',
  ],
  olevel: [
    'Agriculture', 'Biology', 'Chemistry', 'Physics', 'Combined Science',
    'Environmental Science', 'Computer Science',
    'Geography', 'History', 'Religious and Moral Education',
    'Heritage Studies', 'Sociology',
    'Commerce', 'Accounts', 'Business Studies', 'Economics', 'Entrepreneurship',
    'English Language', 'Shona', 'Ndebele', 'French',
    'Physical Education and Sport', 'Art and Design', 'Music', 'Drama and Theatre Arts',
    'Food and Nutrition', 'Fashion and Fabrics', 'Building Technology',
    'Technical Graphics', 'Metal Technology', 'Wood Technology',
    'Home Economics', 'Automotive Technology',
  ],
  alevel: [
    'Mathematics', 'Further Mathematics', 'Statistics',
    'Physics', 'Chemistry', 'Biology', 'Agricultural Science', 'Environmental Science',
    'Computer Science', 'Food Science and Technology',
    'History', 'Geography', 'Heritage Studies', 'Religious Studies',
    'Economics', 'Accounting', 'Business Studies', 'Entrepreneurship',
    'Sociology', 'Global Perspectives',
    'Literature in English', 'Divinity', 'Shona', 'Ndebele',
    'Art and Design', 'Music', 'Drama and Theatre Arts',
    'Technical Graphics', 'Fashion, Fabrics and Design',
  ],
}

const GRADES_BY_LEVEL: Record<string, string[]> = {
  primary: ['Grade 5', 'Grade 6', 'Grade 7'],
  olevel: ['Form 1', 'Form 2', 'Form 3', 'Form 4'],
  alevel: ['Lower 6', 'Upper 6'],
}

const HERITAGE_THEMES = [
  'Local environment & ecology',
  'Indigenous farming & food systems',
  'Community health & nutrition',
  'Water & sanitation',
  'Traditional technology & craft',
  'Cultural heritage & oral traditions',
  'Entrepreneurship & local economy',
  'Energy & natural resources',
  'Disaster risk & climate resilience',
  'Wildlife & biodiversity conservation',
  'Gender & community empowerment',
]

interface GeneratedPackage {
  subject: string
  grade: string
  topic: string
  heritage_theme: string
  template: string
  whatsappText: string
}

interface Props {
  upgradeHref: string
}

export default function SbpPackageGenerator({ upgradeHref }: Props) {
  const [level, setLevel] = useState<'primary' | 'olevel' | 'alevel'>('olevel')
  const [subject, setSubject] = useState('')
  const [grade, setGrade] = useState('')
  const [topic, setTopic] = useState('')
  const [heritageTheme, setHeritageTheme] = useState('')
  const [loading, setLoading] = useState(false)
  const [pkg, setPkg] = useState<GeneratedPackage | null>(null)
  const [error, setError] = useState('')
  const [isPremiumError, setIsPremiumError] = useState(false)
  const [copied, setCopied] = useState(false)

  function handleLevelChange(newLevel: 'primary' | 'olevel' | 'alevel') {
    setLevel(newLevel)
    setSubject('')
    setGrade('')
  }

  async function generate(e: React.FormEvent) {
    e.preventDefault()
    if (!subject || !grade || !topic.trim()) {
      setError('Please fill in all required fields')
      return
    }
    setLoading(true)
    setError('')
    setPkg(null)
    setIsPremiumError(false)
    try {
      const res = await fetch('/api/ai-teacher/sbp-template', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ subject, grade, topic: topic.trim(), heritage_theme: heritageTheme || undefined }),
      })
      const data = await res.json()
      if (res.status === 403 && data.upgrade) { setIsPremiumError(true); return }
      if (!res.ok) { setError(data.error ?? 'Failed to generate package'); return }
      setPkg(data)
    } catch {
      setError('Network error — please try again')
    } finally {
      setLoading(false)
    }
  }

  function downloadPackage() {
    if (!pkg) return
    const content = [
      `ZIMSEC SCHOOL-BASED PROJECT PACKAGE`,
      `Generated by ZimLearn AI (MaFundi)`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Subject: ${pkg.subject}`,
      `Level/Form: ${pkg.grade}`,
      `Topic: ${pkg.topic}`,
      `Heritage Theme: ${pkg.heritage_theme}`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      pkg.template,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `IMPORTANT: This is a model example for guidance only.`,
      `Write your own project in YOUR OWN WORDS based on`,
      `YOUR community, observations, and experiences.`,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `ZimLearn AI — Zimbabwe's AI Teacher | zimlearn.app`,
    ].join('\n')
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `SBP-${pkg.subject}-${pkg.grade}-${pkg.topic.replace(/\s+/g, '-').substring(0, 35)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  function shareWhatsApp() {
    if (!pkg) return
    const encoded = encodeURIComponent(pkg.whatsappText)
    window.open(`https://wa.me/?text=${encoded}`, '_blank', 'noopener,noreferrer')
  }

  async function copyWhatsApp() {
    if (!pkg) return
    await navigator.clipboard.writeText(pkg.whatsappText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">

      {/* Premium gate */}
      {isPremiumError && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-amber-300 dark:border-amber-700 p-8 text-center shadow-lg">
          <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center">
            <Lock size={28} className="text-white" />
          </div>
          <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-2">Upgrade to Access SBP Packages</h2>
          <p className="text-slate-600 dark:text-slate-400 mb-6 max-w-md mx-auto">
            SBP Packages are available on the Starter, Pro, and Elite plans. Upgrade to generate unlimited complete SBP documents for any subject and topic.
          </p>
          <div className="flex gap-3 justify-center flex-wrap">
            <Link
              href={upgradeHref}
              className="flex items-center gap-2 bg-gradient-to-r from-amber-400 to-orange-500 hover:from-amber-500 hover:to-orange-600 text-white font-semibold px-6 py-3 rounded-xl transition-all shadow-md"
            >
              <Crown size={16} />
              Upgrade Now
            </Link>
            <Link
              href="/student/projects/examples"
              className="flex items-center gap-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-medium px-6 py-3 rounded-xl transition-all"
            >
              <BookOpen size={16} />
              Free Examples
            </Link>
          </div>
        </div>
      )}

      {/* Generator form */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6">
        <h2 className="text-lg font-semibold text-slate-800 dark:text-white mb-5 flex items-center gap-2">
          <Bot size={18} className="text-green-500" />
          Configure Your SBP Package
        </h2>

        <form onSubmit={generate} className="space-y-5">
          {/* Level tabs */}
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Education Level <span className="text-red-500">*</span>
            </label>
            <div className="flex rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
              {(['primary', 'olevel', 'alevel'] as const).map((lvl) => (
                <button
                  key={lvl}
                  type="button"
                  onClick={() => handleLevelChange(lvl)}
                  className={`flex-1 py-2.5 text-sm font-medium transition-all ${
                    level === lvl
                      ? 'bg-green-600 text-white'
                      : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700'
                  }`}
                >
                  {lvl === 'primary' ? 'Primary' : lvl === 'olevel' ? 'O-Level' : 'A-Level'}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                Subject <span className="text-red-500">*</span>
              </label>
              <select
                value={subject}
                onChange={e => setSubject(e.target.value)}
                required
                className="w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
              >
                <option value="">Select subject…</option>
                {SUBJECTS_BY_LEVEL[level].map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                Form / Grade <span className="text-red-500">*</span>
              </label>
              <select
                value={grade}
                onChange={e => setGrade(e.target.value)}
                required
                className="w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
              >
                <option value="">Select form/grade…</option>
                {GRADES_BY_LEVEL[level].map(g => <option key={g} value={g}>{g}</option>)}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Project Topic <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              value={topic}
              onChange={e => setTopic(e.target.value)}
              placeholder="e.g. The Effect of Solar Energy on Reducing Firewood Use in Rural Homes"
              required
              className="w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
            />
            <p className="mt-1 text-xs text-slate-400">Be specific — the more detail you give, the better the package</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Heritage Theme <span className="text-xs text-slate-400 font-normal">(strongly recommended for HBC alignment)</span>
            </label>
            <select
              value={heritageTheme}
              onChange={e => setHeritageTheme(e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
            >
              <option value="">Select a heritage theme…</option>
              {HERITAGE_THEMES.map(t => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>

          {error && (
            <p className="text-sm text-red-600 bg-red-50 dark:bg-red-950/30 px-3 py-2 rounded-lg">{error}</p>
          )}

          <button
            type="submit"
            disabled={loading || !subject || !grade || !topic.trim()}
            className="flex items-center gap-2 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-semibold px-6 py-3 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
          >
            {loading
              ? <><Loader2 size={16} className="animate-spin" /> Generating Package…</>
              : <><Package size={16} /> Generate SBP Package <ArrowRight size={16} /></>
            }
          </button>
        </form>
      </div>

      {/* Loading state */}
      {loading && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-10 text-center">
          <div className="w-14 h-14 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-green-500 to-emerald-600 flex items-center justify-center animate-pulse">
            <Bot size={24} className="text-white" />
          </div>
          <p className="text-slate-700 dark:text-slate-300 font-semibold mb-1">MaFundi is building your SBP package…</p>
          <p className="text-sm text-slate-500">Generating a complete ZIMSEC-aligned project for {subject} — {grade}. Takes 20–30 seconds.</p>
        </div>
      )}

      {/* Generated package */}
      {pkg && !loading && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-green-300 dark:border-green-700 overflow-hidden shadow-lg">
          {/* Package header */}
          <div className="bg-gradient-to-r from-green-600 to-emerald-700 p-5 text-white">
            <div className="flex items-start justify-between gap-4 flex-wrap">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <Package size={16} />
                  <span className="text-sm font-medium opacity-90">SBP Package — ZIMSEC HBC Aligned</span>
                </div>
                <h3 className="text-lg font-bold">{pkg.topic}</h3>
                <p className="text-sm opacity-80 mt-0.5">{pkg.subject} · {pkg.grade} · {pkg.heritage_theme}</p>
              </div>
              {/* Action buttons */}
              <div className="flex gap-2 flex-wrap">
                <button
                  onClick={downloadPackage}
                  className="flex items-center gap-1.5 bg-white/20 hover:bg-white/30 text-white text-sm font-medium px-3 py-2 rounded-xl transition-all"
                >
                  <Download size={14} /> Download .txt
                </button>
                <button
                  onClick={shareWhatsApp}
                  className="flex items-center gap-1.5 bg-[#25D366] hover:bg-[#1ebe5a] text-white text-sm font-semibold px-3 py-2 rounded-xl transition-all"
                >
                  <Share2 size={14} /> Share on WhatsApp
                </button>
              </div>
            </div>
          </div>

          {/* HBC compliance badge */}
          <div className="bg-green-50 dark:bg-green-950/20 border-b border-green-200 dark:border-green-800 px-5 py-3 flex flex-wrap items-center gap-4 text-sm">
            <span className="flex items-center gap-1.5 text-green-700 dark:text-green-400 font-medium">
              <CheckCircle size={14} /> ZIMSEC SBP Guidelines Compliant
            </span>
            <span className="flex items-center gap-1.5 text-green-700 dark:text-green-400 font-medium">
              <CheckCircle size={14} /> Heritage-Based Curriculum 2024–2030
            </span>
            <span className="flex items-center gap-1.5 text-amber-700 dark:text-amber-400 font-medium">
              <Sparkles size={14} className="text-amber-500" /> Inspiration only — write your own original work
            </span>
          </div>

          {/* Package content */}
          <div className="p-6">
            <div className="prose prose-sm dark:prose-invert max-w-none
              prose-headings:text-slate-900 dark:prose-headings:text-white
              prose-h1:text-xl prose-h2:text-lg prose-h3:text-base
              prose-blockquote:border-l-4 prose-blockquote:border-green-400 prose-blockquote:bg-green-50 dark:prose-blockquote:bg-green-950/20 prose-blockquote:px-4 prose-blockquote:py-2 prose-blockquote:rounded-r-xl prose-blockquote:text-slate-700 dark:prose-blockquote:text-slate-300
              prose-strong:text-slate-900 dark:prose-strong:text-white
              prose-ul:text-slate-700 dark:prose-ul:text-slate-300
              prose-p:text-slate-700 dark:prose-p:text-slate-300
            ">
              <ReactMarkdown>{pkg.template}</ReactMarkdown>
            </div>
          </div>

          {/* Footer actions */}
          <div className="border-t border-slate-100 dark:border-slate-800 p-5 bg-slate-50 dark:bg-slate-800/50">
            <div className="flex flex-wrap gap-3 items-center justify-between">
              <p className="text-sm text-slate-600 dark:text-slate-400">
                Share this package or save it to your device
              </p>
              <div className="flex gap-2 flex-wrap">
                <button
                  onClick={copyWhatsApp}
                  className="flex items-center gap-1.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white border border-slate-300 dark:border-slate-600 px-4 py-2 rounded-xl transition-all"
                >
                  {copied ? <><CheckCircle size={14} className="text-green-500" /> Copied!</> : <><Share2 size={14} /> Copy for WhatsApp</>}
                </button>
                <button
                  onClick={downloadPackage}
                  className="flex items-center gap-1.5 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-white border border-slate-300 dark:border-slate-600 px-4 py-2 rounded-xl transition-all"
                >
                  <Download size={14} /> Save as text
                </button>
                <button
                  onClick={shareWhatsApp}
                  className="flex items-center gap-1.5 bg-[#25D366] hover:bg-[#1ebe5a] text-white text-sm font-semibold px-4 py-2 rounded-xl transition-all"
                >
                  <Share2 size={14} /> WhatsApp
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
